# Generated by Django 4.0.1 on 2022-01-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_alter_todo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Not Urgent and Not Important'), (1, 'Not Urgent and Important'), (2, 'Urgent and Not Important'), (3, 'Urgent and Important')], default=0, max_length=1),
        ),
    ]
